"""sixth  Migration

Revision ID: 16dfc2b3bea8
Revises: 4512ce8c65cb
Create Date: 2022-05-09 20:34:34.936614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16dfc2b3bea8'
down_revision = '4512ce8c65cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_upvotes')
    op.drop_table('user_downvotes')
    op.add_column('pitch_types', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.add_column('pitch_types', sa.Column('upvotes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitch_types', 'upvotes')
    op.drop_column('pitch_types', 'downvotes')
    op.create_table('user_downvotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch_types.id'], name='user_downvotes_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_downvotes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_downvotes_pkey')
    )
    op.create_table('user_upvotes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch_types.id'], name='user_upvotes_pitch_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_upvotes_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_upvotes_pkey')
    )
    # ### end Alembic commands ###
