"""second  Migration

Revision ID: 4512ce8c65cb
Revises: 56042b3ea800
Create Date: 2022-05-09 08:24:04.310972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4512ce8c65cb'
down_revision = '56042b3ea800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_types', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('pitch_types_pitch_author_fkey', 'pitch_types', type_='foreignkey')
    op.create_foreign_key(None, 'pitch_types', 'users', ['user_id'], ['id'])
    op.drop_column('pitch_types', 'pitch_author')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_types', sa.Column('pitch_author', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pitch_types', type_='foreignkey')
    op.create_foreign_key('pitch_types_pitch_author_fkey', 'pitch_types', 'users', ['pitch_author'], ['id'])
    op.drop_column('pitch_types', 'user_id')
    # ### end Alembic commands ###
