"""sixth  Migration

Revision ID: cf20321ba73b
Revises: 16dfc2b3bea8
Create Date: 2022-05-10 06:19:54.492561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf20321ba73b'
down_revision = '16dfc2b3bea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_downvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pitch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pitch_id'], ['pitch_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('pitch_types', 'downvotes')
    op.drop_column('pitch_types', 'upvotes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitch_types', sa.Column('upvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('pitch_types', sa.Column('downvotes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_table('user_upvotes')
    op.drop_table('user_downvotes')
    # ### end Alembic commands ###
